// This file was automatically generated by penny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/pnsafonov/penny

package unexported

import "fmt"

func myTypeInspect(s *myType) string {
	return fmt.Sprintf("%#v", s)
}
